dist: xenial
sudo: required
language: c

branches:
  only:
  - v8.8
  - v8.9
  - v8.10

cache:
  apt: true
  directories:
  - $HOME/.opam

addons:
  apt:
    packages:
    - gcc-multilib

env:
  global:
  - OPAMJOBS="2"
  - OPAMROOTISOK="true"
  - OPAMYES="true"
  - NJOBS="2"
  - COQ_REPOS="https://github.com/ejgallego/coq.git"
  - COQ_BRANCH="v8.10"
  - COMPILER="ocaml-base-compiler.4.07.1"
  # Main test suites
  matrix:
  - TEST_TARGET="build"   COMPILER="ocaml-base-compiler.4.07.0"  LOCAL_COQ="yes"
  - TEST_TARGET="test"    COMPILER="ocaml-base-compiler.4.07.1"  LOCAL_COQ="yes" EXTRA_OPAM="coq-mathcomp-ssreflect"
  - TEST_TARGET="js-dune" COMPILER="ocaml-variants.4.07.1+32bit" LOCAL_COQ="yes" EXTRA_OPAM="js_of_ocaml js_of_ocaml-lwt"
  - TEST_TARGET="test"    COMPILER="ocaml-base-compiler.4.07.1"                  EXTRA_OPAM="coq.8.10.dev coq-mathcomp-ssreflect"

install:
- sudo curl -sL https://github.com/ocaml/opam/releases/download/2.0.4/opam-2.0.4-x86_64-linux -o /usr/bin/opam
- sudo chmod 755 /usr/bin/opam
- opam init -c "$COMPILER" --disable-sandboxing
- opam switch set "$COMPILER"
- eval $(opam env)
# OPAM 2 seems quite broken here
- opam config set-global jobs $NJOBS
# Core dev repo, to remove on stable releases
- opam repos add coq-core-dev http://coq.inria.fr/opam/core-dev
- opam repos add coq-extra-dev http://coq.inria.fr/opam/extra-dev
# Install deps for coq-serapi
- opam pin add ppx_deriving_yojson --dev
- opam pin add -n --kind=path coq-serapi .
- opam install --deps-only --ignore-constraints-on=ppx_deriving_yojson -j $NJOBS coq-serapi
- opam pin remove coq-serapi
# - opam install --ignore-constraints-on=yojson yojson.1.7.0 ppx_deriving_yojson.3.3
- opam list
- >
  if [[ -v LOCAL_COQ ]]; then
    git clone --depth=3 -b "$COQ_BRANCH" "$COQ_REPOS" "$HOME/coq-$COQ_BRANCH" &&
    opam pin add coq --kind=path "$HOME/coq-$COQ_BRANCH"
  fi
- if [[ -v EXTRA_OPAM ]]; then opam install --ignore-constraints-on=coq $EXTRA_OPAM; fi

script:
- set -e
- echo 'Building SerAPI...' && echo -en 'travis_fold:start:serapi.build\\r'
- make "$TEST_TARGET"
- ls -lR _build/install/default/ || true
- ls -lR _build/default/sertop/*.js || true
- echo -en 'travis_fold:end:serapi.build\\r'
